spring.application.name=ACPeltierBackend

server.port=8080
server.address=0.0.0.0

app.apiKey=${APP_APIKEY}
app.deviceKey=${APP_DEVICEKEY}

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC